<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: code.proto

namespace GPBMetadata;

class Code
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a94020a0a636f64652e70726f746f120970726f746f64617461221d0a0d" .
            "53656172636852657175657374120c0a047465787418012001280922350a" .
            "0e536561726368526573706f6e736512230a046461746118012003280b32" .
            "152e70726f746f646174612e436f646544657461696c22540a0a436f6465" .
            "44657461696c120a0a026964180120012803120d0a057469746c65180220" .
            "012809120c0a046c616e67180320012809120c0a04746167731804200128" .
            "09120f0a07636f6e74656e7418052001280932470a04436f6465123f0a06" .
            "53656172636812182e70726f746f646174612e5365617263685265717565" .
            "73741a192e70726f746f646174612e536561726368526573706f6e736522" .
            "00620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

