JwtSecret = "2aEtVr"

[Server]
  Addr = ":3000"

[Account]
  Name = "kicoe"
  Pass = "$2a$14$z2KmWYDadZlBpSpGg30hB.akygxHkSDnjJ4838A9eBlNYSrZ7XSo."

[Database]
  Driver = "mysql"
  Source = "root:123456@tcp(127.0.0.1:3306)/blog?charset=utf8mb4"

[OSS]
  Region = ""
  Bucket = ""
  AccessKeyId = ""
  AccessKeySecret = ""
  RoleArn = ""

[Cache]
  Addr = "localhost:6379"
