isDev = true
JwtSecret = "z8xgbmykvNViZkhwZnc1Tr/JnKNqNfbBThPYxiVBLgE="

[System]
  AttachmentCDN = "https://raw.githubusercontent.com/moonprism/cdn/master/blog_attachments/"
  TokenExpiryHours = 72

[Server]
  Addr = ":3000"

[Database]
  Driver = "sqlite"
  Source = "test.db"
  # Driver = "mysql"
  # Source = "root:123456@tcp(127.0.0.1:3306)/blog?charset=utf8mb4"

[FTS]
  Source = "test_fts.db"

[OSS]
  Region = ""
  Bucket = ""
  AccessKeyId = ""
  AccessKeySecret = ""
  RoleArn = ""

[Cache]
  # Addr = "localhost:3306"

[Github]
  ImagesApi = "https://api.github.com/repos/moonprism/cdn/contents/blog_attachments"
