version: "3.1"

services:
  web:
    image: nginx
    ports:
      - "8023:8023"
      - "8033:8033"
    volumes:
      - ./read:/var/www/html/read
      - ./write/web/public:/var/www/html/write
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
    networks:
      - app
  php:
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./read:/var/www/html/read
      - ./log/read:/var/www/html/log
    working_dir: /var/www/html/read
    networks:
      - app
  write-api:
    build: ./write
    ports:
      - "8044:8044"
    volumes:
      - ./data/write/static:/www/static
      - ./log/write:/www/log
    networks:
      - app
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6380:6379"
    volumes:
      - ./data/redis:/data
    networks:
      - app
  mysql:
    build: ./docker/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/password"
    secrets:
      - password
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./log/mysql:/var/log/mysql
    networks:
      - app
  meilisearch:
    image: getmeili/meilisearch
    ports:
      - "7700:7700"
    volumes:
      - ./data/meilisearch:/data.ms
    networks:
      - app

secrets:
  password:
    file: password.txt

networks:
  app:
