version: "3.1"

services:
  web:
    image: nginx
    ports:
      - "8023:8023"
      - "8033:8033"
    volumes:
      - ./read:/var/www/html/read
      - ./write/web/public:/var/www/html/write
      - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
    networks:
      - app
  php:
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./read:/var/www/html/read
      - ./log/read:/var/www/html/log
    working_dir: /var/www/html/read
    networks:
      - app
  write-api:
    build: ./write
    ports:
      - "8044:8044"
    volumes:
      - ./write/options:/www/options
      - ./data/write/static:/www/static
      - ./data/write/riot-index:/www/data/riot-index
      - ./log/write:/www/log
    networks:
      - app
  redis:
    image: redis
    ports:
      - "6380:6379"
    networks:
      - app
  mysql:
    build: ./docker/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/password"
    secrets:
      - password
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./log/mysql:/var/log/mysql
    networks:
      - app

secrets:
  password:
    file: password.txt

networks:
  app:
