# build services by docker
version: "3.1"

services:

  web:
    build: ./web/app
    volumes:
      - ./web/app:/web
    working_dir: /web
    network_mode: "host"
    command: /bin/sh -c "npm install ; npm run build" # dev

  api:
    build:
      context: ../docker/golang
      # args:
      #   http_proxy: "http://localhost:8080"
      #   https_proxy: "http://localhost:8080"
      # network: host
    volumes:
      - ./:/app
      - ./.mod:/go/pkg/mod
    working_dir: /app
    # environment:
    #   http_proxy: "http://localhost:8080"
    #   https_proxy: "http://localhost:8080"
    # network_mode: "host"
    command: /bin/sh -c "swag init ; go mod tidy ; GOOS=linux GOARCH=amd64 go build -o linux_amd64_api -v"
