# build services by docker
version: "3.1"

services:

  web:
    build: ./web/app
    volumes:
      - ./web/app:/web
    working_dir: /web
    command: /bin/sh -c "npm install ; npm run build"

  api:
    image: golang:1.19.2-alpine
    volumes:
      - ./:/app
      # - ./mod:/go/pkg/mod
    working_dir: /app
    # environment:
    #   http_proxy: "http://localhost:8080"
    #   https_proxy: "http://localhost:8080"
    # network_mode: "host"
    command: /bin/sh -c "go mod tidy ; GOOS=linux GOARCH=amd64 go build -o linux_amd64_api -v"
