// Code generated by protoc-gen-go. DO NOT EDIT.
// source: code.proto

package protodata

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SearchRequest struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_code_1b6a06cc2d575d95, []int{0}
}
func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (dst *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(dst, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type SearchResponse struct {
	Data                 []*CodeDetail `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *SearchResponse) Reset()         { *m = SearchResponse{} }
func (m *SearchResponse) String() string { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()    {}
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_code_1b6a06cc2d575d95, []int{1}
}
func (m *SearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchResponse.Unmarshal(m, b)
}
func (m *SearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchResponse.Marshal(b, m, deterministic)
}
func (dst *SearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchResponse.Merge(dst, src)
}
func (m *SearchResponse) XXX_Size() int {
	return xxx_messageInfo_SearchResponse.Size(m)
}
func (m *SearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchResponse proto.InternalMessageInfo

func (m *SearchResponse) GetData() []*CodeDetail {
	if m != nil {
		return m.Data
	}
	return nil
}

type CodeDetail struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Lang                 string   `protobuf:"bytes,3,opt,name=lang,proto3" json:"lang,omitempty"`
	Tags                 string   `protobuf:"bytes,4,opt,name=tags,proto3" json:"tags,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CodeDetail) Reset()         { *m = CodeDetail{} }
func (m *CodeDetail) String() string { return proto.CompactTextString(m) }
func (*CodeDetail) ProtoMessage()    {}
func (*CodeDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_code_1b6a06cc2d575d95, []int{2}
}
func (m *CodeDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CodeDetail.Unmarshal(m, b)
}
func (m *CodeDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CodeDetail.Marshal(b, m, deterministic)
}
func (dst *CodeDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CodeDetail.Merge(dst, src)
}
func (m *CodeDetail) XXX_Size() int {
	return xxx_messageInfo_CodeDetail.Size(m)
}
func (m *CodeDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_CodeDetail.DiscardUnknown(m)
}

var xxx_messageInfo_CodeDetail proto.InternalMessageInfo

func (m *CodeDetail) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CodeDetail) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CodeDetail) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *CodeDetail) GetTags() string {
	if m != nil {
		return m.Tags
	}
	return ""
}

func (m *CodeDetail) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*SearchRequest)(nil), "protodata.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "protodata.SearchResponse")
	proto.RegisterType((*CodeDetail)(nil), "protodata.CodeDetail")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CodeClient is the client API for Code service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CodeClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
}

type codeClient struct {
	cc *grpc.ClientConn
}

func NewCodeClient(cc *grpc.ClientConn) CodeClient {
	return &codeClient{cc}
}

func (c *codeClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, "/protodata.Code/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CodeServer is the server API for Code service.
type CodeServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
}

func RegisterCodeServer(s *grpc.Server, srv CodeServer) {
	s.RegisterService(&_Code_serviceDesc, srv)
}

func _Code_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodeServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodata.Code/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodeServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Code_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protodata.Code",
	HandlerType: (*CodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _Code_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "code.proto",
}

func init() { proto.RegisterFile("code.proto", fileDescriptor_code_1b6a06cc2d575d95) }

var fileDescriptor_code_1b6a06cc2d575d95 = []byte{
	// 221 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x8f, 0x39, 0x4f, 0x03, 0x31,
	0x10, 0x85, 0xd9, 0x23, 0x41, 0x19, 0x44, 0x8a, 0x11, 0x48, 0x03, 0x55, 0xb4, 0x34, 0xa1, 0xd9,
	0x22, 0x94, 0x14, 0x14, 0x20, 0xd1, 0x9b, 0x5f, 0x60, 0xd6, 0xa3, 0xc5, 0xd2, 0xca, 0x0e, 0xf1,
	0x20, 0xf1, 0xf3, 0x91, 0xc7, 0x2c, 0x87, 0x94, 0xca, 0x73, 0xf9, 0xbd, 0xef, 0x01, 0x0c, 0xd1,
	0x71, 0xbf, 0x3f, 0x44, 0x89, 0xb8, 0xd2, 0xc7, 0x59, 0xb1, 0xdd, 0x0d, 0x9c, 0xbf, 0xb0, 0x3d,
	0x0c, 0x6f, 0x86, 0xdf, 0x3f, 0x38, 0x09, 0x22, 0xb4, 0xc2, 0x9f, 0x42, 0xd5, 0xa6, 0xda, 0xae,
	0x8c, 0xd6, 0xdd, 0x3d, 0xac, 0xe7, 0xa3, 0xb4, 0x8f, 0x21, 0x31, 0xde, 0x42, 0x9b, 0xbf, 0x53,
	0xb5, 0x69, 0xb6, 0x67, 0xbb, 0xcb, 0xfe, 0x47, 0xb0, 0x7f, 0x8c, 0x8e, 0x9f, 0x58, 0xac, 0x9f,
	0x8c, 0x9e, 0x74, 0x02, 0xf0, 0x3b, 0xc3, 0x35, 0xd4, 0xde, 0xa9, 0x78, 0x63, 0x6a, 0xef, 0xf0,
	0x02, 0x16, 0xe2, 0x65, 0x62, 0xaa, 0xd5, 0xaf, 0x34, 0x19, 0x62, 0xb2, 0x61, 0xa4, 0xa6, 0x40,
	0xe4, 0x5a, 0xc1, 0xec, 0x98, 0xa8, 0xfd, 0x06, 0xb3, 0x63, 0x42, 0x82, 0xd3, 0x21, 0x06, 0xe1,
	0x20, 0xb4, 0xd0, 0xf1, 0xdc, 0xee, 0x9e, 0xa1, 0xcd, 0xae, 0xf8, 0x00, 0xcb, 0x82, 0x8e, 0xf4,
	0x07, 0xf2, 0x5f, 0xe4, 0xeb, 0xab, 0x23, 0x9b, 0x92, 0xb3, 0x3b, 0x79, 0x5d, 0xea, 0xee, 0xee,
	0x2b, 0x00, 0x00, 0xff, 0xff, 0x2d, 0x67, 0xbd, 0xf9, 0x40, 0x01, 0x00, 0x00,
}
